### ISSUE TITLE
Blockchain stuck at some wallets. Mainnodes and Bitnodes are O.K. Here are some systeminfos and logfiles

### ISSUE THREAD

**Issue by szenekonzept** [EuropecoinEUORG/EuropecoinV2#1]
My logging at 21-2-2016 16:34 UTC:
1) working fine, current block 902212
2) Windows 64bit
3) connected 167.114.224.82:2828
send version message: version 60014, blocks=902212, us=86.89.215.230:2828, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82:2828
connection timeout
trying connection 68.224.11.146:2828 lastseen=2.9hrs
connection timeout
trying connection 79.156.34.66:2828 lastseen=8.8hrs
connection timeout
trying connection 83.39.147.235:2828 lastseen=7.5hrs
connection timeout
trying connection 84.248.120.126:2828 lastseen=34.9hrs
connection timeout
trying connection 188.165.2.147:2828 lastseen=22.9hrs
connection timeout
trying connection [2a02:a442:6e6e:0:bdcb:d3c9:7fd1:8db9]:2828 lastseen=1028.8hrs
connection timeout
trying connection 95.116.246.10:2828 lastseen=47.9hrs
connection timeout
trying connection 5.146.248.41:2828 lastseen=24.0hrs
connection timeout
trying connection 84.248.120.126:2828 lastseen=34.9hrs
connection timeout
trying connection 79.156.34.66:2828 lastseen=8.8hrs
connection timeout
trying connection 98.255.195.184:2828 lastseen=109.8hrs
connection timeout
trying connection 77.28.249.19:2828 lastseen=520.0hrs
connection timeout
trying connection 78.193.40.205:2828 lastseen=53.9hrs
connection timeout
trying connection 194.166.38.181:2828 lastseen=104.1hrs
connection timeout
trying connection 83.39.147.235:2828 lastseen=7.5hrs
connection timeout
trying connection 212.25.58.46:2828 lastseen=16.2hrs
connection timeout
trying connection 51.175.41.140:2828 lastseen=5.1hrs
connection timeout
trying connection 79.198.15.224:2828 lastseen=2.8hrs
connection timeout
trying connection 85.214.102.254:2828 lastseen=7.0hrs
connection timeout
trying connection 78.193.40.205:2828 lastseen=53.9hrs
connection timeout
trying connection 188.78.212.219:2828 lastseen=19.3hrs
connection timeout
trying connection 167.114.224.82:2828 lastseen=376686.7hrs
connected 167.114.224.82:2828
send version message: version 60014, blocks=902212, us=86.89.215.230:2828, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82:2828
trying connection 81.164.117.101:2828 lastseen=54.1hrs
connection timeout
trying connection 72.39.10.246:2828 lastseen=55.4hrs
connection timeout
trying connection 87.185.21.84:2828 lastseen=326.5hrs
connection timeout
trying connection 178.115.129.50:2828 lastseen=102.0hrs
connection timeout
trying connection 79.198.15.224:2828 lastseen=2.8hrs
connection timeout
trying connection 84.197.58.26:2828 lastseen=26.6hrs
connection timeout
trying connection 84.161.253.113:2828 lastseen=545.4hrs
connection timeout
trying connection 83.39.147.235:2828 lastseen=7.5hrs
connection timeout
trying connection 95.116.219.62:2828 lastseen=90.0hrs
connection timeout
trying connection 217.38.117.198:2828 lastseen=412.0hrs
connection timeout
trying connection 77.28.241.80:2828 lastseen=9.5hrs
connection timeout
trying connection 84.248.120.126:2828 lastseen=35.0hrs
connection timeout
trying connection 194.166.38.181:2828 lastseen=104.1hrs
connection timeout
trying connection 83.39.147.235:2828 lastseen=7.5hrs
connection timeout
trying connection 84.197.58.26:2828 lastseen=26.6hrs
connection timeout

4) Jerry  (backbonejb)

1) STUCK: yes block 901964
2) Operating system: Linux 64bit
3) last 30 lines of your debug.log file

CheckStake() : new proof-of-stake block found  
  hash: 610a71d110ff839b8fc84a81e3b36ef2dea026e6cbd79e47174243594f6b3fe3 
proofhash: 03260711e7ead70ec56c40f081267f16c55d9a5b902d799afadebee45b734235  
target: 057ff6eb50000000000000000000000000000000000000000000000000000000
CBlock(hash=610a71d110ff839b8fc84a81e3b36ef2dea026e6cbd79e47174243594f6b3fe3, ver=6, hashPrevBlock=8ad9719266c49d8656bb4a57396f9824ba49e19dfb48867962f0c5300976ce30, hashMerkleRoot=b9d51f319841d35a19847ea5759b5ae88a9740b943e299b5efc22f72d60f6fe3, nTime=1456073026, nBits=1e02a254, nNonce=0, vtx=2, vchBlockSig=304402200e3d70a697a07d50ef30061e27b78c994724726f8d6da9320bd5394ead576cc8022043f6a0602cacbad9ca1ee686ef4dcaf696b81e9f9491cc6e77197f63688f3a68)
  Coinbase(hash=ada5a2c8ba, nTime=1456073026, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 034dc30d)
    CTxOut(empty)
    CTxOut(empty)
  Coinstake(hash=04e370353d, nTime=1456073026, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(46ae8ec294, 1), scriptSig=3045022100fb24275dcb91d4)
    CTxOut(empty)
    CTxOut(nValue=12564.82005534, scriptPubKey=0392a90b9674cfd00c11e480c1e552d709366353805c249cd51bfef1d3fc0bcebf OP_CHECKSIG)
  vMerkleTree: ada5a2c8ba 04e370353d b9d51f3198 
out 12564.82005534
ERROR: AcceptBlock() : block's timestamp is too far in the future
ERROR: ProcessBlock() : AcceptBlock FAILED
ERROR: CheckStake() : ProcessBlock, block not accepted
CheckStake() : new proof-of-stake block found  
  hash: 27c3579ee81678ee6e11ba6b4f1ce0f7f561ea4bf48cac0c7b4963bc5bcc8e90 
proofhash: 03260711e7ead70ec56c40f081267f16c55d9a5b902d799afadebee45b734235  
target: 057ff6eb50000000000000000000000000000000000000000000000000000000
CBlock(hash=27c3579ee81678ee6e11ba6b4f1ce0f7f561ea4bf48cac0c7b4963bc5bcc8e90, ver=6, hashPrevBlock=8ad9719266c49d8656bb4a57396f9824ba49e19dfb48867962f0c5300976ce30, hashMerkleRoot=425091317689a64b77336df0e9d7488b0ea60193cf4a7ccdc13ee1f0aa2cf43e, nTime=1456073026, nBits=1e02a254, nNonce=0, vtx=2, vchBlockSig=3045022100d8c963004e182b53356a7924be0d2e166f97adb1c5bc4b6651b5eda5a38c37200220642bd96f1029be50ce1e4602a59781f39ad854b8f5883e8fd77ed910750d5590)
  Coinbase(hash=ada5a2c8ba, nTime=1456073026, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 034dc30d)
    CTxOut(empty)
    CTxOut(empty)
  Coinstake(hash=48c55d91f2, nTime=1456073026, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(46ae8ec294, 1), scriptSig=3045022100d069da3cd7cee4)
    CTxOut(empty)
    CTxOut(nValue=12564.82005534, scriptPubKey=0392a90b9674cfd00c11e480c1e552d709366353805c249cd51bfef1d3fc0bcebf OP_CHECKSIG)
  vMerkleTree: ada5a2c8ba 48c55d91f2 4250913176 
out 12564.82005534
ERROR: AcceptBlock() : block's timestamp is too far in the future
ERROR: ProcessBlock() : AcceptBlock FAILED
ERROR: CheckStake() : ProcessBlock, block not accepted
1. Stuck: yes - block 901844
2. OS: Windows 10 32bit
3. Last 30 lines of debug.log file:

ERROR: AcceptBlock() : block's timestamp is too far in the future
ERROR: ProcessBlock() : AcceptBlock FAILED
ERROR: CheckStake() : ProcessBlock, block not accepted
connection timeout
trying connection 78.193.40.205:2828 lastseen=7.1hrs
CheckStake() : new proof-of-stake block found  
  hash: 796e602081b18d9645477393385366653eefa4a408304e39276a5d6ecc471198 
proofhash: 001aaa38953ba2ec3de4dd8cff41cf2668e03f2a04fe2407a0988c8566e79ce4  
target: 001c8ffe37000000000000000000000000000000000000000000000000000000
CBlock(hash=796e602081b18d9645477393385366653eefa4a408304e39276a5d6ecc471198, ver=6, hashPrevBlock=81a66786e143e822861b1be46cedf79917b6152e6f362519f9b2503dfaf714f9, hashMerkleRoot=e6f7eee0105a7ab98a8b06cc84f296c14c2fd6ce4de97ceb98ae51b8294473bc, nTime=1456076461, nBits=1e0fffff, nNonce=0, vtx=2, vchBlockSig=304402203ffcacaeb8085e98b294c3bc3f6f413ac198f3f88b1804c7281322e1ae28744302206a0eedcf73d17fb36b3f6e3678cecc5b7f51797ab351142c0c7d1c1df9af09a7)
  Coinbase(hash=6ce5986ede, nTime=1456076461, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 03d5c20d)
    CTxOut(empty)
    CTxOut(empty)
  Coinstake(hash=3aa9aa29e4, nTime=1456076461, ver=1, vin.size=1, vout.size=3, nLockTime=0)
    CTxIn(COutPoint(fe51ec8c54, 1), scriptSig=30440220542f8d88aee13eb8)
    CTxOut(empty)
    CTxOut(nValue=583.38, scriptPubKey=02911c4ff0cf219fe557636fa327467d537cf016d754c1d8ba2949935abb250e3d OP_CHECKSIG)
    CTxOut(nValue=583.3967688, scriptPubKey=02911c4ff0cf219fe557636fa327467d537cf016d754c1d8ba2949935abb250e3d OP_CHECKSIG)
  vMerkleTree: 6ce5986ede 3aa9aa29e4 e6f7eee010 
out 1166.7767688
ERROR: AcceptBlock() : block's timestamp is too far in the future
ERROR: ProcessBlock() : AcceptBlock FAILED
ERROR: CheckStake() : ProcessBlock, block not accepted
CheckStake() : new proof-of-stake block found  
  hash: d75ad1594a2275864aadc2b4d5157f2db150b910e61911a163c4e515ed4b7c3c 
proofhash: 001aaa38953ba2ec3de4dd8cff41cf2668e03f2a04fe2407a0988c8566e79ce4  
target: 001c8ffe37000000000000000000000000000000000000000000000000000000
CBlock(hash=d75ad1594a2275864aadc2b4d5157f2db150b910e61911a163c4e515ed4b7c3c, ver=6, hashPrevBlock=81a66786e143e822861b1be46cedf79917b6152e6f362519f9b2503dfaf714f9, hashMerkleRoot=da7401d16a75024f4ed2d53f02e2bbf9a9b952e8265a5a6cc1e9c7f5b823a1d9, nTime=1456076461, nBits=1e0fffff, nNonce=0, vtx=2, vchBlockSig=304502210090dc23f06d9d2e90d51b4f146917f0f94524674cad44ecf925a6e517d1d2bdca02205a1c0a912d2f7d86c03062b9cb17a0dda12b0749c4df24f23d3007346ee27afe)
  Coinbase(hash=6ce5986ede, nTime=1456076461, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 03d5c20d)
    CTxOut(empty)
    CTxOut(empty)
  Coinstake(hash=b8b43660c4, nTime=1456076461, ver=1, vin.size=1, vout.size=3, nLockTime=0)
    CTxIn(COutPoint(fe51ec8c54, 1), scriptSig=304402207999c2047575955b)
    CTxOut(empty)
    CTxOut(nValue=583.38, scriptPubKey=02911c4ff0cf219fe557636fa327467d537cf016d754c1d8ba2949935abb250e3d OP_CHECKSIG)
    CTxOut(nValue=583.3967688, scriptPubKey=02911c4ff0cf219fe557636fa327467d537cf016d754c1d8ba2949935abb250e3d OP_CHECKSIG)
  vMerkleTree: 6ce5986ede b8b43660c4 da7401d16a 
out 1166.7767688
ERROR: AcceptBlock() : block's timestamp is too far in the future
ERROR: ProcessBlock() : AcceptBlock FAILED
ERROR: CheckStake() : ProcessBlock, block not accepted
1. Stuck: yes - block 901964
2. Windows 7 Prof 64bit
3. Last 30 lines of debug.log file:

connection timeout
trying connection 79.56.59.152:2828 lastseen=20.3hrs
trying connection [2604:880:c:af::286c]:2828 lastseen=376688.3hrs
connection timeout
trying connection 81.164.117.101:2828 lastseen=57.7hrs
connection timeout
trying connection 68.224.11.146:49449 lastseen=376688.3hrs
connection timeout
trying connection 51.175.41.140:2828 lastseen=4.5hrs
connection timeout
trying connection 167.114.224.79:61408 lastseen=376688.3hrs
connection timeout
trying connection 95.76.145.63:2828 lastseen=6.7hrs
connection timeout
trying connection [2600:8801:2e80:22d:9d0e:6ba8:869f:9393]:52676 lastseen=376688.3hrs
connection timeout
trying connection 79.56.59.152:2828 lastseen=20.3hrs
connection timeout
trying connection 5.57.241.181:49286 lastseen=376688.3hrs
connection timeout
trying connection 95.116.206.65:2828 lastseen=7.3hrs
connection timeout
trying connection 86.89.215.230:1120 lastseen=376688.3hrs
connection timeout
trying connection 79.156.34.66:2828 lastseen=9.2hrs
connection timeout
trying connection 130.43.18.79:49544 lastseen=376688.3hrs
connection timeout
trying connection 188.78.212.219:2828 lastseen=8.0hrs
connection timeout
trying connection 96.229.213.68:63194 lastseen=376688.3hrs
connection timeout
trying connection 86.89.215.230:2828 lastseen=4.6hrs
connection timeout
trying connection 188.78.212.219:53199 lastseen=376688.3hrs
connection timeout
trying connection 79.198.25.79:2828 lastseen=50.7hrs
connection timeout
trying connection 212.25.58.45:51456 lastseen=376688.3hrs
connection timeout
trying connection 5.146.248.41:2828 lastseen=7.4hrs
connection timeout
trying connection 84.248.120.126:50078 lastseen=376688.3hrs
connection timeout
connection timeout
trying connection 93.181.28.158:2828 lastseen=106.9hrs
trying connection 85.240.75.83:59638 lastseen=376688.3hrs
connection timeout
connection timeout
trying connection 45.55.195.243:49154 lastseen=376688.3hrs
trying connection 86.89.215.230:2828 lastseen=4.6hrs
connection timeout
connection timeout
trying connection [2a02:a442:6e6e:0:41b6:6152:6b90:ae7b]:51995 lastseen=376688.3hrs
trying connection 95.116.246.10:2828 lastseen=49.5hrs
connection timeout
connection timeout
trying connection 72.39.10.246:52173 lastseen=376688.3hrs
trying connection 195.252.80.210:2828 lastseen=4.5hrs
connection timeout
connection timeout
trying connection 178.50.66.44:18774 lastseen=376688.3hrs
trying connection 86.89.215.230:2828 lastseen=4.6hrs
connection timeout
trying connection 95.116.205.125:63814 lastseen=376688.3hrs
connection timeout
trying connection 77.236.185.9:2828 lastseen=19.9hrs
connection timeout
trying connection 5.9.67.48:41542 lastseen=376688.3hrs
connection timeout
trying connection 145.133.99.29:2828 lastseen=9.7hrs
connection timeout
connection timeout
trying connection 77.236.185.9:2828 lastseen=19.9hrs
connection timeout
trying connection 51.175.41.140:2828 lastseen=4.5hrs
connection timeout
trying connection 79.132.111.195:2828 lastseen=4.6hrs
connection timeout
trying connection 95.116.205.125:2828 lastseen=19.1hrs
connection timeout
trying connection 95.76.145.63:2828 lastseen=6.7hrs
connection timeout
trying connection 51.175.41.140:2828 lastseen=4.5hrs
1. Stuck - Yes
   2.Windows 32bit Pro
   3.Last 30 lines
   Stuck on block 901790

connection timeout
trying connection 78.193.40.205:2828 lastseen=18.4hrs
connection timeout
trying connection 85.214.102.254:2828 lastseen=23.5hrs
connection timeout
trying connection 95.117.63.246:2828 lastseen=42.9hrs
connection timeout
trying connection 5.146.248.41:2828 lastseen=2.3hrs
connection timeout
trying connection 84.90.209.26:2828 lastseen=25.5hrs
connection timeout
trying connection 51.175.41.140:2828 lastseen=7.4hrs
connection timeout
trying connection 83.39.147.235:2828 lastseen=3.1hrs
connection timeout
trying connection 79.132.111.195:2828 lastseen=17.5hrs
connection timeout
trying connection 86.89.215.230:2828 lastseen=14.7hrs
connection timeout
trying connection 137.135.57.119:2828 lastseen=2.7hrs
connection timeout
RandAddSeed() 218328 bytes
trying connection 79.132.111.195:2828 lastseen=17.5hrs
connection timeout
trying connection 77.59.139.161:2828 lastseen=14.4hrs
connection timeout
trying connection 111.88.26.82:2828 lastseen=232.0hrs
connection timeout
trying connection 51.175.41.140:2828 lastseen=7.4hrs
connection timeout
trying connection 145.133.99.29:2828 lastseen=22.6hrs
connection timeout
trying connection 51.175.41.140:2828 lastseen=7.4hrs
Name : wildduck
1. Stuck - Yes, on block 901964
2. Windows 7 Enterprise 64bit 
3. Last 30 lines:

connection timeout
trying connection 95.76.145.63:2828 lastseen=4.5hrs
connection timeout
trying connection 212.25.58.47:2828 lastseen=88.3hrs
connection timeout
trying connection 95.76.145.63:2828 lastseen=4.5hrs
connection timeout
trying connection 188.165.2.147:2828 lastseen=2.5hrs
connection timeout
trying connection 5.146.248.41:2828 lastseen=2.2hrs
connection timeout
trying connection 137.135.57.119:2828 lastseen=2.6hrs
connection timeout
trying connection 77.236.185.9:2828 lastseen=16.0hrs
connection timeout
trying connection 87.143.232.73:2828 lastseen=64.6hrs
connection timeout
trying connection 137.135.57.119:2828 lastseen=2.6hrs
connection timeout
trying connection 91.153.109.149:2828 lastseen=7.0hrs
connection timeout
trying connection 79.198.3.248:2828 lastseen=47.4hrs
connection timeout
trying connection 93.181.28.158:2828 lastseen=118.4hrs
connection timeout
trying connection 188.165.2.147:2828 lastseen=2.5hrs
connection timeout
trying connection 91.153.109.149:2828 lastseen=7.0hrs
connection timeout
trying connection 5.146.248.41:2828 lastseen=2.2hrs
1. Yes ?  (block 902229  6connections again,latest block says generated 5 seconds ago, but in debug log it has gone back to block 901964 ? )  and last confirmed block was early yesterday.
2. Windows 7 x64

3.
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket recv error 10054
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
Flushed 64 addresses to peers.dat  0ms
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
socket closed
disconnecting node 167.114.224.82
trying connection 167.114.224.82 lastseen=0.0hrs
connected 167.114.224.82
send version message: version 60014, blocks=902229, us=0.0.0.0:0, them=167.114.224.82:2828, peer=167.114.224.82:2828
RandAddSeed() 223176 bytes
receive version message: version 60014, blocks=901964, us=5.57.241.181:55029, them=167.114.224.82:2828, peer=167.114.224.82:2828
Flushed 64 addresses to peers.dat  0ms
Flushed 64 addresses to peers.dat  0ms
RandAddSeed() 224128 bytes
Flushed 64 addresses to peers.dat  31ms
RandAddSeed() 226720 bytes
Flushed 64 addresses to peers.dat  31ms
Flushed 64 addresses to peers.dat  0ms
RandAddSeed() 223384 bytes
Flushed 64 addresses to peers.dat  0ms
RandAddSeed() 222968 bytes
Flushed 64 addresses to peers.dat  31ms
Flushed 64 addresses to peers.dat  0ms
RandAddSeed() 223696 bytes
Flushed 64 addresses to peers.dat  0ms
RandAddSeed() 224248 bytes
Flushed 64 addresses to peers.dat  0ms
Flushed 64 addresses to peers.dat  0ms
RandAddSeed() 232336 bytes
Flushed 64 addresses to peers.dat  10ms
RandAddSeed() 229112 bytes
Flushed 64 addresses to peers.dat  40ms
Flushed 64 addresses to peers.dat  5ms
RandAddSeed() 230464 bytes
Flushed 64 addresses to peers.dat  0ms
RandAddSeed() 229760 bytes

**Comment by Infernoman** [comment]
Currently I am on block 902231 the last 2 blocks were generated by me using the most recent updates. I am trying to release a windows client for this shortly. But anyone who is building the client themselves should be safe to upgrade.
