### ISSUE TITLE
Reorganize failed

### ISSUE THREAD

**Issue by Infernoman** [EuropecoinEUORG/EuropecoinV2#4]
Reorganize failed. Needs to be fixed for when an invalid block is received. the blockchain has to be reloaded.
Could be wrong about this investigating it more later after i sleep.

**Comment by szenekonzept** [comment]
log from Bitcointalk:

03/09/16 22:11:58 REORGANIZE
03/09/16 22:11:58 REORGANIZE: Disconnect 0 blocks; 1b67371b1bc994fdd0d0..1b67371b1bc994fdd0d0
03/09/16 22:11:58 REORGANIZE: Connect 1 blocks; 1b67371b1bc994fdd0d0..e6b13c206bbe5c569435
03/09/16 22:11:58 ERROR: CBlock::ReadFromDisk() : GetHash() doesn't match index
03/09/16 22:11:58 ERROR: Reorganize() : ReadFromDisk for connect failed
03/09/16 22:11:58 InvalidChainFound: invalid block=069a77a71c2eb7a92fec  height=904249  trust=9033905499440008  blocktrust=663050720  date=03/09/16 22:12:48
03/09/16 22:11:58 InvalidChainFound:  current best=1b67371b1bc994fdd0d0  height=901530  trust=9029826315651899  blocktrust=1358037385  date=02/18/16 05:03:10
03/09/16 22:11:58 ERROR: SetBestChain() : Reorganize failed
03/09/16 22:11:58 ERROR: AcceptBlock() : AddToBlockIndex failed
03/09/16 22:11:58 ERROR: ProcessBlock() : AcceptBlock FAILED
03/09/16 22:12:11 trying connection 173.32.89.136:2828 lastseen=377100.4hrs

hope that helps

**Comment by szenekonzept** [comment]
keep your time, sleep is important, thank you for  helping
